services:

    php:
      build:
        dockerfile: docker/php/Dockerfile
      volumes:
        - .:/app
      depends_on:
        - postgres_database
    nginx:
      image: nginx:1.25.0
      ports:
      - 80:80
      volumes:
        - .:/app
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php

    postgres_database:
      container_name: postgres
      image: postgres:16
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      volumes:
        - ./docker/psql/init.sql:/docker-entrypoint-initdb.d/init.sql
